# d3hack example configuration

[resolution_hack]
SectionEnabled = true
# - 900 -> 1600x900  (aliases "900p" | "default" | "unchanged")
# - 1080 -> 1920x1080 (aliases "1080p" | "FHD")
# - 1440 -> 2560x1440 (aliases "1440p" | "2K" | "QHD")
OutputTarget = 1080
# Minimum resolution scale (percentage) to apply. 100% = locked resolution.
MinResScale = 85
# MUST be enabled for higher resolutions to avoid crashes above 1152p (2048x1152)!
ClampTextures2048 = true

[seasons]
SectionEnabled = true
AllowOnlinePlay = false
SeasonNumber = 37

[challenge_rifts]
SectionEnabled = true
MakeRiftsRandom = true
RiftRangeStart = 0
RiftRangeEnd = 28

[events]
SectionEnabled = true
# Season map modes: "MapOnly" | "OverlayConfig" | "Disabled"
# - MapOnly: apply the season's mapped theme (Seasons 14-37 only), ignore flags below.
# - OverlayConfig: apply map, then OR with any event flags below.
# - Disabled: ignore the map and use flags below as-is.
SeasonMapMode = "OverlayConfig"
IgrEnabled = false
AnniversaryEnabled = false
EasterEggWorldEnabled = false
DoubleRiftKeystones = false
DoubleBloodShards = false
DoubleTreasureGoblins = false
DoubleBountyBags = false
RoyalGrandeur = false
LegacyOfNightmares = false
TriunesWill = false
Pandemonium = false
KanaiPowers = false
TrialsOfTempests = false
ShadowClones = false
FourthKanaisCubeSlot = false
EtherealItems = false
SoulShards = false
SwarmRifts = false
SanctifiedItems = false
DarkAlchemy = false
NestingPortals = false

[rare_cheats]
SectionEnabled = true
MovementSpeedMultiplier = 1.5
GuaranteedLegendaryChance = false
DropAnyItems = true
InstantPortalAndBookOfCain = true
NoCooldowns = true
InstantCubeAndCraftsAndEnchants = true
SocketGemsToAnySlot = false
AutoPickup = false
EquipAnySlot = false

[overlays]
SectionEnabled = true
BuildLockerWatermark = false
FPSLabel = false
VariableResLabel = true

[loot_modifiers]
SectionEnabled = true
DisableAncientDrops = false
DisablePrimalAncientDrops = false
DisableTormentDrops = false
DisableTormentCheck = true
SuppressGiftGeneration = true
ForcedILevel = 70
TieredLootRunLevel = 150
AncientRank = "Primal"

[debug]
SectionEnabled = false
EnablePubFileDump = false
EnableErrorTraces = true
EnableDebugFlags = false
