# d3hack-nx example configuration

[seasons]
SectionEnabled = true
AllowOnlinePlay = false
SeasonNumber = 37

[challenge_rifts]
SectionEnabled = true
MakeRiftsRandom = true
RiftRangeStart = 0
RiftRangeEnd = 9

[events]
SectionEnabled = true
IgrEnabled = false
AnniversaryEnabled = false
EasterEggWorldEnabled = false
DoubleRiftKeystones = true
DoubleBloodShards = true
DoubleTreasureGoblins = true
DoubleBountyBags = true
RoyalGrandeur = false
LegacyOfNightmares = true
TriunesWill = false
Pandemonium = false
KanaiPowers = false
TrialsOfTempests = false
ShadowClones = false
FourthKanaisCubeSlot = false
EthrealItems = false
SoulShards = false
SwarmRifts = false
SanctifiedItems = false
DarkAlchemy = true
NestingPortals = false

[rare_cheats]
SectionEnabled = true
DrawFPS = true
DrawVariableResolution = true
Target1080pResolution = true
MovementSpeedMultiplier = 1.5
GuaranteedLegendaryChance = false
DropAnyItems = true
InstantPortalAndBookOfCain = true
NoCooldowns = true
InstantCubeAndCraftsAndEnchants = true
SocketGemsToAnySlot = false
AutoPickup = false
EquipAnySlot = false

[overlays]
SectionEnabled = true
BuildLockerWatermark = true
DDMLabels = true
FPSLabel = true
VariableResLabel = true

[loot_modifiers]
SectionEnabled = true
DisableAncientDrops = false
DisablePrimalAncientDrops = false
DisableTormentDrops = false
DisableTormentCheck = true
SuppressGiftGeneration = true
ForcedILevel = 70
TieredLootRunLevel = 150
AncientRank = "Primal"

[debug]
SectionEnabled = false
EnablePubFileDump = false
EnableErrorTraces = true
EnableDebugFlags = false
